### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Tassadar921** [Tassadar921/Colonizadar#111]
# Cahier des charges - Landing Page Colonizadar

---

## 1. Présentation du projet

**Nom du projet :** Colonizadar  
**Contexte :** Le projet consiste à créer une landing page pour **donner de la visibilité au jeu Colonizadar** et **attirer des utilisateurs**.  
**Initiateur du projet :** @Tassadar921

---

## 2. Objectifs de la landing page

**Objectif principal :** Inciter les visiteurs à cliquer sur le bouton **"Jouer"** pour accéder au jeu Colonizadar.  
**Objectifs secondaires :**  
- Encourager le partage du jeu pour **attirer d'autres utilisateurs**.  
- Favoriser le **bouche-à-oreille** autour du jeu.  
**Objectif chiffré :** Aucun objectif quantitatif spécifié pour le moment.

---

## 3. Contenus à inclure

**3.1 Textes**  
- **Titre principal (à reformuler si besoin) :**  
  *Partie en Cours – Colonizadar*  
- **Description (accroche) :**  
  *Jouez à Colonizadar en temps réel ! Développez votre empire, élaborez des stratégies avec ou contre les autres, et conquérez la carte dans ce jeu multijoueur.*  
- **Mots-clés (SEO) :**  
  jeu en ligne, gameplay, Colonizadar partie, stratégie multijoueur, construction empire, jeu temps réel

**3.2 Logo / Identité visuelle**  
- **À insérer dès que disponible.**

**3.3 Visuels**  
- **À insérer dès que disponibles :** captures d’écran, illustrations, vidéo, etc.

**3.4 Bouton "Jouer"**  
- Redirige vers l’URL définie par la variable d’environnement `import.meta.env.VITE_FRONT_URI`

**3.5 Éléments de réassurance (à prévoir)**  
- Page Instagram  
- Serveur Discord  
- Autres communautés ou réseaux sociaux pertinents

---

## 4. Charte graphique et technique

**4.1 Couleurs**  
La palette principale repose sur la gamme suivante, avec une prédominance de la couleur `--color-primary-500: #fe795d` :

```css
:root {
  --color-primary-50: #fff5f2;
  --color-primary-100: #fff1ee;
  --color-primary-200: #ffe4de;
  --color-primary-300: #ffd5cc;
  --color-primary-400: #ffbcad;
  --color-primary-500: #fe795d; /* Couleur principale */
  --color-primary-600: #ef562f;
  --color-primary-700: #eb4f27;
  --color-primary-800: #cc4522;
  --color-primary-900: #a5371b;
  --shadow-color: #00000040;
  --shadow-main: 0 35px 35px var(--shadow-color);
}
```

- Couleurs globales pour textes : gris foncé (mode clair), blanc (mode sombre)  
- Fond global : gris clair en mode clair, gris foncé en mode sombre

**4.2 Typographie**  
- Typographie système standard

**4.3 Responsive**  
- Landing page 100% responsive (mobile, tablette, desktop)  
- Framework Tailwind CSS v4 utilisé

**4.4 Inspirations / exemples**  
- Inspiration design : [meetsponsors.com](https://meetsponsors.com/)  
- Développement sur template Svelte v5 (sans SvelteKit), TypeScript, multilingue via `svelte-i18n` (par URL), SEO optimisé, composants UI shadcn-svelte

---

## 5. Fonctionnalités techniques

**5.1 Framework**  
- Svelte v5, Tailwind CSS v4, TypeScript, ShadCN ([shadcn-svelte](https://www.shadcn-svelte.com/docs))

**5.2 Hébergement**  
- Géré par @Tassadar921

**5.3 Intégrations**  
- Aucune intégration spécifique prévue pour le moment

**5.4 Analytics**  
- Aucun outil d’analytics ou suivi prévu pour l’instant

**5.5 RGPD**  
- Bandeau cookies conforme à prévoir  
- Pas de formulaire, donc pas de consentement formulaire requis

---

## 6. Tests & validation

**6.1 Navigateurs et appareils**  
- Tests sur navigateurs Chromium (Chrome, Opera, Brave...)  
- Tests sur Firefox  
- Tests responsive mobiles/tablettes

**6.2 Tests A/B**  
- Non prévu pour l’instant (version unique)

**6.3 Validation**  
- Validation finale par @Tassadar921

---

## 7. Planning

**7.1 Délais**  
- Première maquette : ASAP  
- Développement complet : mi-été 2025 (début juillet idéalement)  
- Mise en ligne : juste après développement (début juillet 2025)

**7.2 Contraintes / événements**  
- Aucune contrainte particulière pour le moment
